[versions]
project-version = "0.0.1"

plugin-kotlin-version = "1.6.10"

plugin-javafx-version = "0.0.10"
javafx-version = "17"
materialfx-version = "11.13.5"

slf4j-version = "1.7.36"
log4j-version = "2.17.2"

[libraries]
# bom
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom" }

# kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }

# javafx
materialfx = { group = "io.github.palexdev", name = "materialfx", version.ref = "materialfx-version" }

# log
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j-version" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j-version" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4j-version" }

[bundles]
log4j = ["log4j-api", "log4j-core", "log4j-slf4j-impl"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin-kotlin-version" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "plugin-javafx-version" }